### PR TITLE
added flac support

### PR DESCRIPTION
**Pull request by gsora**
this commit adds the needed exoplayer libraries, allowing flac files
streaming.
the .aar file can be found in the musikcube-bin repository too, for
archival purposes.

### CODE REVIEW

**Comment by clangen** [comment]
Awesome. Is it possible to update the PR to use the `aar` file that we are distributing in the `musikcube-bin` submodule? It'd be great to completely keep binaries out of this particular repo.

**Comment by gsora** [comment]
Uhm, there are already some `aar` files under `app/libs`:

```
-rw-r--r-- 1 gsora gsora  39K 15 dic 13.28 android-taskrunner-0.5.aar
-rw-r--r-- 1 gsora gsora 592K 15 dic 13.28 exoplayer-extension-flac-release-v2.aar
-rw-r--r-- 1 gsora gsora  55K 15 dic 13.28 videocache-2.8.0-clangen-5.aar
```

Do you want those under `musikcube-bin` too?

**Comment by gsora** [comment]
I've modified the Gradle script to fetch the needed `aar` from `musikcube-bin`.

**Comment by clangen** [comment]
Oh yeah, good point! Those others libs should also be in `musikcube-bin`. :) I can take care of that in a separate commit. 

Also, I just realized that updating to the `master` branch of the `musikcube-bin` submodule pulls in newer versions of some of our windows binaries; this will break the VS2017 build, but I'll fix that in a subsequent commit.

Planning to merge this later this evening when I have a bit of time, so I can simultaneously fix the Windows problems.

**Comment by gsora** [comment]
Great ✨

After this merge I'll try to get my hands dirty with some Kotlin, I have some ideas - mainly usability fixes.

**Comment by clangen** [comment]
@gsora -- I ended up just creating and merging a separate commit because I had to do a bit more minor surgery to `musikcube-bin`, which caused a conflict in the sub-module commit hash in your branch.

I tested FLAC playback and it's working!

https://github.com/clangen/musikcube/commit/d5924f936fd32c113544fbd1a345d07ec0167d37

**Pull request closed without merging**
