### PR TITLE
Removed bash dependency from shell scripts

### PR DESCRIPTION
**Pull request by hectorm**
Current shell scripts can be easily replaced by others that do not require bash. I have also added "exec" to replace the current shell with the invoked process.

### CODE REVIEW

**Comment by clangen** [comment]
Can the scripts be updated so they `cd` back to the original directory when the app is closed (or is otherwise terminated)? As a user it would be annoying to start `musikcube` in directory `A`, only to be dropped into directory `B` when the app finishes. :)

**Comment by hectorm** [comment]
The shell script runs in a different subshell, so it does not change the current directory of the user's interactive shell.

Have you been able to reproduce other behavior?

**Comment by clangen** [comment]
Just tried it, seems to work as expected! My shell scripting abilities are basically non-existent... I wonder what I was doing way back when I wrote this script originally that made me think I needed to do a `pushd` followed by a `popd`? :thinking:

Oh well, thanks for the patch! Will merge.

**Comment by hectorm** [comment]
It is possible you were sourcing the script with `.` or `source`.  In that case the commands run in the current shell.

**Pull request merged**
