### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by UM-Li**
This is a draft Simplified Chinese translation. Two points of issues:

### Line 30: "tracks in"

Would you please provide some context for this string? Supposing "track" to mean "piece of music", in English we'd say "**tracks in** [location]" but in Chinese Mandarin it's usually "[location] **中的曲目**". There seems to be a word order issue here and the string may need to include a variable.

### Line 79: "seek playback (don't scrub)"

Could you please explain what "to seek" and "to scrub" mean in this context?

### CODE REVIEW

**Comment by clangen** [comment]
Hi there! Apologies for the delay here, work and end of year holidays has been keeping me very busy. First of all, thank you very much for the new translation!

For Line 30 I just checked in a fix into master to address the formatting issue. https://github.com/clangen/musikcube/commit/60175bb0200fadee208d357fd24b2bb4be8195a2

For 79: seek and scrub are terms used to describe how fast forwarding works. Seeking is buffered, and will not update the playback position until the user has completed interacting with the control. Scrubbing, on the other hand, updates the audio immediately and generally sounds like the audio is being played at an increased speed. I may not doing a good job describing it. The audacity manual describes it as follows -- maybe this helps?

> Scrubbing changes the audio position without skipping. Seeking changes the audio position, skipping over audio to move more quickly

You can also try to enable this setting then use the `o` key to fast forward and see if you can hear the difference.

**Comment by Siheyuan98** [comment]
Thank you, I have uploaded a final draft for merging.
 
Take your time :-)

**Comment by UM-Li** [comment]
Thank you. I've uploaded a final draft for merging.
On second thought I deleted the dimension specifications at the end.  I'm not sure how all the strings are positioned and displayed, therefore leaving the typesetting task to the program itself.

Take your time :-)

**Comment by clangen** [comment]
Awesome, thank you so much! This will be part of the next release. Note that I changed the base branch, and merged it into `clangen/upgrades-12-2019` to make it easier to track with a set of other changes I've been working on.

**Pull request merged**
