### PR TITLE
Just a heads up!

### PR DESCRIPTION
**Pull request by clangen**
Hey Daniel!

I know you haven't worked on musikcube in a long time, and don't really expect you to accept the pull request, but I just wanted to let you know I've been hacking on the old code for a while now. I ended up changing jobs a while back, so I no longer have a conflict of interest. And I always wanted to finish musikcube.

For better or worse, I ended up stripping a bunch of the functionality I wasn't personally using to make the code base smaller and easier to work with it -- things like the XML/HTTP server were removed for the time being, and the entire UI layer (including win32cpp) was also deleted. I'd like to add the client/server model back at some point soon, but using something more efficient, maybe protocol buffers, and take advantage an existing boost-compatible HTTP server library instead of a home grown one to make maintenance easier. 

I added a multi-platform, curses-based frontend and implemented output devices for Linux (using ALSA) and OS X (using CoreAudio). I was also able to refactor the audio engine to support true gapless playback, and fixed a handful of obscure race conditions along the way.

Also, because your version of the repo is old, I was thinking about promoting mine to a top-level (i.e. non fork) so I have things like ownership of the wiki. Not sure if you'd be cool with this, though, so let me know. :)

Best,
Casey

### CODE REVIEW

**Comment by onnerby** [comment]
Awesome!

You should promote your repo as the master if you are working on it. I just converted the repo from google code to github so that we would not loose any of the old code 😄 
I can delete this repo if you like - or maybe add a README that directs to your repo instead?

**Comment by onnerby** [comment]
Or - https://help.github.com/articles/about-repository-transfers/

**Comment by clangen** [comment]
Oh, neat. A repository transfer sounds good -- that documentation suggests my fork promoted to the "master" fork, and yours would then show up as a fork of mine. Then you wouldn't have to update yours in an anyway, or delete it. 

Am I understanding properly? Should we give it a go? :)

**Comment by onnerby** [comment]
No..Didn't work. You already have that repo
image

**Comment by onnerby** [comment]
Guess I can rename it first and then transfer. 
How do I promote yours?

**Comment by clangen** [comment]
Yeah, hmm. It looks like I have to delete my instance of the project, renaming it won't be enough (see https://github.com/stevenvachon/broquire/issues/3).

What would you think about merging my pull request (I can create another one with more up to date changes), then I can delete my repo and you can transfer ownership then? At that point you can probably fork mine, then revert my changes and force push to your instance if you'd like to preserve your current state of the world. 

Or would you rather keep yours around without any of my code? I'd understand if that's the case.

**Comment by onnerby** [comment]
Just let me know when I can transfer 👍

**Comment by clangen** [comment]
Alright, give it a shot, I just deleted my fork!

**Comment by onnerby** [comment]
Worked 👍

**Comment by clangen** [comment]
Awesome, thank you! You're also still a contributor, which means you should still have commit access. As always, feel free to play with things if you ever get bored. :)

**Pull request merged**
